### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by Murilo001** [kyriosdata/integracao#13]
Quanto à metodologia dos tópicos, eles serão liberados agora no início da disciplina? Seria interessante ter mais tópicos liberados para irmos agilizando e adquirindo mais aproveitamento nas atividades.

**Comment by Murilo001** [comment]
Qual seria o título da issue da atividade 2 do tópico 2?

**Comment by kyriosdata** [comment]
Você está correto Murilo e a intenção é exatamente esta. Novos tópicos serão liberados em breve.

Estou tratando como uma dúvida do tópico 2.

COM APROVEITAMENTO. 👍
