### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by kirebr** [kyriosdata/integracao#14]
Queria deixar como dúvida/sugestão a respeito do trabalho em grupo. Acredito que se trabalhar em dupla ou trio fica mais fácil pro professor corrigir os trabalhos e dar uma atenção maior pra cada trabalho, assim podemos fazer trabalhos melhores e mais refinados .

**Comment by kyriosdata** [comment]
Ola Erik, você tem razão nas suas colocações. Apenas vamos aguardar um pouco mais para "ver" o desenrolar do nosso ensino remoto. Motivo: conforme explicado no encontro síncrono, estas atividades devem ser vistas com cautela, pois induz uma interação entre os estudantes que não está sendo cobrada "nem com o professor", não é verdade? Contudo, registro feito.

COM APROVEITAMENTO. 👍
