### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by kirebr** [kyriosdata/integracao#20]
1 - O que é interessado (stakeholder)?
Um indivíduo ou um grupo que é responsável ou afetado pelo produto de uma tarefa, atividade ou processo.

2 - O que é software?
Entende-se software como sinônimo de produto de software que é o conjunto de programas de computador, procedimentos e possível documentação e dados associados [ISO/IEC/IEEE, 2017]

3 - A seção 7 do Guia identifica a base técnica para a definição dos modelos MPS. Quais são os elementos dessa base?
ISO/IEC/IEEE 12207:2017 - ISO/IEC 20000 - ISO/IEC Família 330xx - NBR ISO 9001:2015 - PNQ® – Prêmio Nacional da Qualidade® - MoProSoft - NMX-I-059/2-NYCE-2011

4 - O Modelo de Referência MPS para Software (MR-MPS-SW) define níveis de maturidade que são uma combinação entre processos e sua capacidade. Quais são os níveis de maturidade?
Nível G - Parcialmente Gerenciado /  Nível F - Gerenciados / Nível E - Parcialmente Definido / Nível D - Definido / Nível C - Totalmente Definido / Nível B - Gerenciado Quantitativamente / Nível A - Em Otimização

5 - O que são processos de projeto?
Os processos de projeto são aqueles que são executados para os projetos de software. Esses projetos podem ser de desenvolvimento de um novo produto, manutenção ou evolução de produto. 

6 - O que são processos organizacionais?
Os processos organizacionais são os processos concebidos para fornecer os recursos necessários para que o projeto/serviço atenda às expectativas e necessidades das partes interessadas da organização.

**Comment by kyriosdata** [comment]
- Melhor seria: G, F, E, D e C. Não estão definidos os níveis B e A. Acredito que deve ter consultado outra referência. 

COM APROVEITAMENTO. 👍
