### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/integracao#22]
**O que é interessado (stakeholder)?**
É o indivíduo ou organização impactado pelo processo, atividade, produto de trabalho ou decisão.

**O que é software?**
Entende-se software como sinônimo de produto de software que é o conjunto de programas de computador, procedimentos e possível documentação e dados associados.

**A seção 7 do Guia identifica a base técnica para a definição dos modelos MPS. Quais são os elementos dessa base?**
Os elementos dessa base são: ISO/IEC/IEEE 12207:2017, ISO/IEC 20000, ISO/IEC família 330xx,NBR ISO 9001:2015, PNQ® – Prêmio Nacional da Qualidade®, MoProSoft - NMX-I-059/2-NYCE-2011,

**O Modelo de Referência MPS para Software (MR-MPS-SW) define níveis de maturidade que são uma combinação entre processos e sua capacidade. Quais são os níveis de maturidade?**
Os níveis são: G - Parcialmente Gerenciado, F - Gerenciados,E - Parcialmente Definido, D - Definido e C - Totalmente Definido

**O que são processos de projeto?**
Os processos de projeto são aqueles que são executados para os projetos de software. Esses projetos podem ser de desenvolvimento de um novo produto, manutenção e evolução de produto. 

**O que são processos organizacionais?**
Os processos organizacionais são os processos concebidos para fornecer os recursos necessários para que o projeto atenda às expectativas e necessidades das partes interessadas da organização.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
