### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by ghost** [kyriosdata/integracao#24]
•O que é interessado (stakeholder)?
É um indivíduo ou organização impactado pelo processo, atividade, produto de trabalho ou decisão.

•O que é software?
É o conjunto de programas de computador, procedimentos, documentação e dados associados.

•A seção 7 do Guia identifica a base técnica para a definição dos modelos MPS. Quais são os elementos dessa base?
São ISO/IEC/IEEE 12207:2017, ISO/IEC 20000, ISO/IEC família 330xx, NBR ISO 9001:2015, Prêmio Nacional da Qualidade® (PNQ), e  MoProSoft - NMX-I-059/2-NYCE-2011.

•O Modelo de Referência MPS para Software (MR-MPS-SW) define níveis de maturidade que são uma combinação entre processos e sua capacidade. Quais são os níveis de maturidade?
os níveis são G (parcialmente gerenciado), F (gerenciado), E (parcialmente definido), D (definido), C (totalmente definido), B (gerenciado quantitativamente), e A (em otimização).

•O que são processos de projeto?
São os processos realizados para desenvolver, manter, ou evoluir um produto de software.

•O que são processos organizacionais?
São processos que servem para fornecer recursos pra que o projeto atenda às expectativas e necessidades das partes interessadas da organização.

**Comment by kyriosdata** [comment]
- Melhor seria: níveis G, F, E, D e C. Você deve ter consultado outra referência, não há os níveis B nem A, conforme sua resposta.

COM APROVEITAMENTO. 👍
