### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/integracao#28]
**Quantas páginas tem o Guia?**
Possui 37 páginas

**Quais são os processos de projeto que fazem parte do nível G?**
Os processos são: Gerência de Projetos, Gerência de Configuração, Engenharia de Requisitos, Projetos e Construção do Produto, Integração do Produto, Verificação e Validação.

**Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)?**
Não, nem todos se repetem, porém os resultados são acumulativos, ou seja, os resultados que aparecem no nível G deverão estar presentes, com as mesmas características ou com evoluções, no nível F e acima.

**É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?**
É esperado que em alguns processos haja evolução em níveis mais elevados, porém para alguns processos é esperado apenas que o processo seja mantido, porém sempre lembrando que os resultados são cumulativos.

**Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?**
O propósito do processo Verificação é confirmar que os produtos de trabalho selecionados atendem aos requisitos especificados pela execução de testes e revisão por pares. Já o propósito do processo Validação é confirmar que um produto ou componente do produto atenderá a seu uso pretendido quando colocado no ambiente operacional.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 

Apenas um pequeno equívoco, mas há mais páginas no Guia. Naturalmente, a intenção foi atendida.
