### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/integracao#31]
(T02)

I. **O que é interessado (stakeholder)?**
Indivíduo ou organização impactado pelo processo, atividade, produto de trabalho ou decisão.

II. **O que é software?**
Entende-se software como sinônimo de produto de software que é o conjunto de programas de computador, procedimentos e possível documentação e dados associados.

III. **A seção 7 do Guia identifica a base técnica para a definição dos modelos MPS. Quais são os elementos dessa base?**
São elementos de tal base técnica as séries de normas **ISO/IEC/IEEE 12207:2017** (sobre processos de ciclo de vida de software) , **ISO/IEC 20000** (referência para a prestação de serviços de Tecnologia da Informação), **ISO/IEC família 330xx** (um framework para a avaliação da qualidade de processos), **NBR ISO 9001:2015** (estabelece requisitos que auxiliam na melhora de processos) e **MoProSoft - NMX-I-059/2-NYCE-2011** (estabelece requisitos para o método de verificação do modelo de processos MoProSoft, criado pela Secretaria de Economia do México e voltado para a indústria de software), além do **PNQ®** (Prêmio Nacional da Qualidade - reconhece empresas de nível classe mundial dentro do Brasil).

IV. **O Modelo de Referência MPS para Software (MR-MPS-SW) define níveis de maturidade que são uma combinação entre processos e sua capacidade. Quais são os níveis de maturidade?**
Os níveis de maturidade são:
- **Nível A** - Em Otimização
- **Nível B** - Gerenciado Quantitativamente
- **Nível C** - Totalmente Definido
- **Nível D** - Definido
- **Nível E** - Parcialmente Definido
- **Nível F** - Gerenciados
- e **Nível G** - Parcialmente Gerenciado

V. **O que são processos de projeto?**
Os **processos de projeto** são aqueles que são executados para os projetos de software. Esses projetos podem ser de desenvolvimento de um novo produto manutenção ou evolução de produto. 

VI. **O que são processos organizacionais?**
Os **processos organizacionais** são os processos concebidos para fornecer os recursos necessários para que o projeto/serviço atenda às expectativas e necessidades das partes interessadas da organização.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
