### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by murilonear** [kyriosdata/integracao#33]
I. O que é interessado (stakeholder)?

Indivíduo ou organização impactado pelo processo,atividade, produto de trabalho ou decisão.

II. O que é software?

Entende-se software como sinônimo de produto de software que é o conjunto de programas de computador, procedimentos e possível documentação e
dados associados.

III. A seção 7 do Guia identifica a base técnica para a definição dos modelos MPS. Quais são os elementos dessa base?

-ISO/IEC/IEEE 12207:2017(Processos, atividades, tarefas, propósito e resultados a serem aplicados durante o ciclo vida do software)
-ISO/IEC 20000 (Padrão de referência para oferecer serviços de Tecnologia da Informação para clientes (internos ou externos) com qualidade)
-ISO/IEC família 330xx (Conjunto de normas que fornecem um framework para avaliação de características de qualidade de processos)
-NBR ISO 9001:2015 (Estabelece requisitos que auxiliam a melhoria dos processos internos, voltados principalmente para liderança, planejamento, apoio,operação e avaliação de desempenho da organização)
-PNQ® – Prêmio Nacional da Qualidade®(Processo de avaliação com objetivo de selecionar empresas que se destacam pela sua excelência em gestão)
-MoProSoft - NMX-I-059/2-NYCE-2011 (Estabelece os requisitos para o método de verificação do modelo de processos MoProSoft, desenvolvido como parte do programa ProSoft da Secretaria de Economia para a indústria de
software do México)

IV. O Modelo de Referência MPS para Software (MR-MPS-SW) define níveis de maturidade que são uma combinação entre processos e sua capacidade. Quais são os níveis de maturidade?

Os níveis de  maturidade no Modelo de Referência MPS para Software são:
Nível A: Em Otimização
Nível B: Gerenciado Quantitativamente
Nível C: Totalmente Definido
Nível D: Definido
Nível E: Parcialmente Definido
Nível F: Gerenciados
Nível G: Parcialmente Gerenciado

V. O que são processos de projeto?

Os processos de projeto são aqueles que são executados para os projetos de
software. Esses projetos podem ser de desenvolvimento de um novo produto,
manutenção ou evolução de produto. 

VI. O que são processos organizacionais?

Os processos organizacionais são os processos concebidos para fornecer os
recursos necessários para que o projeto/serviço atenda às expectativas e
necessidades das partes interessadas da organização

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
