### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by Campusero123** [kyriosdata/integracao#35]
i. Stakeholder é o indivíduo ou organização que é impactado por um processo, uma atividade, um produto ou decisão advindas do projeto.

 ii. Software se entende como um produto que consiste no conjunto de programas de computador, procedimentos, documentação e dados associados.

iii. Os elementos da base técnica consistem em conjuntos de normas nacionais e internacionais, que definem modelos, e regras para construção e manutenção de processos.

iv. Os níveis de maturidade descrevem o quão detalhado e completo é um processo. Esses níveis vão de G a A, e são descritos respectivamente como G - Parcialmente Gerenciado, F - Gerenciado, E - Parcialmente Definido, D - Definido, C - Totalmente Definido, B - Gerenciado Quantitativamente e A - Em Otimização.

 v. Processos são conjuntos de atividades inter-relacionadas que recebem dados e insumos como entrada e geram produtos finais como saída.

vi. São processos executados para atender aos objetivos de negócio e formam a definição do escopo da avaliação.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
