### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by ghost** [kyriosdata/integracao#38]
•Quantas páginas tem o Guia?
O guia tem 49 páginas

•Quais são os processos de projeto que fazem parte do nível G?
Fazem parte do nível G os processos de gerência de projeto, engenharia de requisitos, projeto e construção do produto, integração do produto, verificação e validação.

•Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)?
Sim, os processos de projeto se repetem em todos os níveis desde o G.

•É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?
Em níveis mais elevados, a partir do nível E, há evoluções em determinados processos. Primeiramente nos processos organizacionais, mas a partir do nível D também há evolução nos processos de projeto.

•Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?
Verificação e validação são dois processos realizáveis em conjunto, porém cada um tem um propósito diferente: a verificação tem por objetivo avaliar se o software desenvolvido atende aos seus próprios requisitos, e é realizada pela organização que produz o software; a validação, por outro lado, trata das expectativas do cliente ou usuário final, e nesse processo, o cliente ou usuário final avalia se o produto atende às regras do negócio.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
