### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by kirebr** [kyriosdata/integracao#39]
1 - Quantas páginas tem o Guia?
R: O guia geral de software tem 49 páginas.

2 - Quais são os processos de projeto que fazem parte do nível G?
R: Gerência de Projetos / Engenharia de Requisitos / Projeto e Construção do Produto / Integração do Produto / Verificação e Validação

3 - Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)?
R: Sim, eles se repetem de forma que vai acontecendo um aprimoramento em cada nível. 

4 - É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?
R: Há evoluções ou exigências em níveis mais elevados. Quanto maior o nível, maior é a maturidade do processo e a forma como ele é tratada. 

5 - Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?
R: A Verificação é uma atividade, a qual envolve a análise de um sistema para certificar se este atende aos requisitos funcionais e não funcionais. Já a Validação, é a certificação de que o sistema atende as necessidades e expectativas do cliente. O processo de Validação e Verificação, não são processos separados e independentes.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
