### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/integracao#40]
(T03)

I. **Quantas páginas tem o Guia?**
O Guia possui 49 páginas.

II. **Quais são os processos de projeto que fazem parte do nível G?**
- Gerência de Projetos
- CP-G/F (Projeto)
- Engenharia de Requisitos
- Projeto e Construção do Produto
- Integração do Produto
- Verificação e Validação

III. **Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)?**
Sim, os processos de projeto se repetem em todos os níveis.

IV. **É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?**
Há evoluções ou exigências em níveis mais elevados. No **nível E**, os processos organizacionais de Gerência de Recursos Humanos, Gerência Organizacional e Gerência de Processos sofrem evolução. Já no nível D, todos os processos de projeto sofrem evolução. No nível C, os processos organizacionais de Gerência Organizacional, Medição e Aquisição são evoluídos. Os níveis B e A também possuem evoluções tanto em processos organizacionais quanto em processos de projeto.

V. **Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?**
Enquanto a Verificação serve para checar se o software desenvolvido foi desenvolvido corretamente, a validação assegura que tal software cobre de fato as necessidades inicialmente fornecidas pelo cliente.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 

Embora o CP-G/F esteja "criptografado".
