### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by murilonear** [kyriosdata/integracao#41]
I. Quantas páginas tem o Guia?

O Guia Geral de Software 2020 tem 49 páginas.

II. Quais são os processos de projeto que fazem parte do nível G?
No nível G, existem os processos de Gerência de Projetos, Engenharia de Requisitos, Projeto e Construção do Produto, Integração do Produto e Verificação e Validação.

III. Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)?
OS processos de projeto repetem em todos os níveis, sendo evoluidos a cada nível.

IV. É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?

Em níveis mais elevados são exigidos novos processos, iniciando no nível F que são acrescentados os Processos Organizacionais que são evoluídos já a partir do nível E e são aprimorados de acordo com o nível e também são feitas evoluções nos Processos de Projeto a partir do nível D.

V. Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?

São realizados em conjunto para confirmar que os produtos de trabalho selecionados, atendem aos requisitos específicados. A verificação com o objetivo de saber se o software está sendo feito corretamente, atendendo os requisitos e funcionalidades documentados, se está satisfazendo as especificações que foram levantadas. Já na validação, com o objetivo de saber se os requisitos que estão sendo implementados atendem a regra de negócio do cliente, para validar se o produto vai cumprir com sua finalidade.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
