### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by josimarMorais** [kyriosdata/integracao#42]
1 - Quantas páginas tem o Guia? 
49 páginas

2 - Quais são os processos de projeto que fazem parte do nível G?
Gerência de Projetos, Engenharia de Requisitos, Projeto e Construção do Produto, Integração do Produto e Verificação e Validação.

3 - Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)? 
Sim, os processos de projeto se repetem.

4 - É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?
Há evoluções em níveis mais elevados, por exemplo no nível D.

5 - Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?
O propósito do processo de projeto de Verificação e Validação é confirmar que os produtos de trabalho selecionados atendem aos requisitos especificados. Assim, a Verificação entra como uma atividade a qual envolve a análise dos requisitos especificados para certificar que este atende as requisitos funcionais e não funcionais, enquanto a Validação é responsável pela execução de testes e revisão por pares, e que um produto ou componente do produto atenderá a seu uso pretendido quando colocado no ambiente operacional.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
