### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by cleydsonjr** [kyriosdata/integracao#47]
**1. Quantas páginas tem o Guia?**

Total de 49 páginas

**2. Quais são os processos de projeto que fazem parte do nível G?**

O nível G é composto pelos seguintes processos:

- Gerência de Projetos
- CP-G/F
- Engenharia de Requisitos
- Projeto e Construção do Produto
- Verificação e Validação
- Integração do Produto

**3. Os processos de projeto se repetem em todos os níveis (G, F, E, D e C)?**

Os processos se repetem, porém há uma evolução nas exigências.

**4. É esperado que todos os processos sejam executados da mesma forma, independente do nível, ou há evoluções ou exigências em níveis mais elevados, dependendo do processo?**

Naturalmente há evolução nas exigências já que uma maturidade maior é esperada

**5. Há dois processos de projeto semelhantes até no nome, Verificação e Validação. Qual a diferença entre eles?**
O processo de Verificação está relacionado a análise de aderência aos requisitos de software levantados (funcionais e não funcionais). Já a Validação é o processo usado para garantir que o software desenvolvido efetivamente atende às necessidades do cliente.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
