### ISSUE TITLE
08

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/integracao#69]
Requisitos de Software
É a área responsável por elicitar, analisar, documentar, verificar e validar, garantir a qualidade e gerenciar os requisitos explícitos e implícitos, necessários para a construção do software, durante todo o seu ciclo de vida deste produto.

Projeto de Software
É a área responsável por realizar  todo o planejamento anterior ao desenvolvimento do Software, visando determinar os componentes e sua organização(projeto arquitetônico) e descrever o comportamento desejados desses, gerando documentos/artefatos que serão guias para os programadores.

Construção de Software
É a área da Engenharia de Software onde o software será construído, envolvendo codificação, verificação, testes de unidade e integração e depuração de erros. Essa área está diretamente relacionada com todas as outras, principalmente com a de Projeto e Teste.

Teste de Software
É a área responsável por avaliar a corretude do software durante todo o seu ciclo de vida, visando revelar falhas/bugs antes da entrega do produto, a fim de que sejam corrigidas para atingir a qualidade desejada.

Manutenção de Software
É a área responsável por realizar reparos, melhorias e otimização do software desenvolvido, preservando sua integridade. Há quem defenda que essa área pode ser executada até mesmo antes da entrega do produto.

Gerência de Configuração de Software
É a área responsável por controlar a evolução do produto, mantendo sua integridade e estabilidade, identificando seus elementos a fim de gerenciar, controlar,  verificar e registrar  todas as mudanças que ocorrerem durante o ciclo de vida do software.

Gerência de Engenharia de Software
É a área responsável por gerenciar todo o processo de produção do Software em todo o seu ciclo de vida, executando atividades como planejamento, coordenação, medição, monitoramento e controle, visando garantir que os produtos e serviços de engenharia de software sejam entregues de forma eficiente e eficaz.

Processo de Engenharia de Software
São um conjunto de atividades que transformam entradas em saídas, ou seja, está relacionada a toda atividade de trabalho realizada para desenvolver, manter e operar software.

Métodos e Modelos de Engenharia de Software
Os métodos são procedimentos, técnicas que determinam como fazer o software e fornecem uma abordagem organizada e sistemática para sua produção. Já os modelos são representações ou abstrações dos objetos e atividades envolvidas nos processos de software.

Qualidade de Software
É a área que se preocupa com a capacidade do produto de software de satisfazer as necessidades implícitas sob condições especificadas e explícitas, e como o grau em que esse produto de software atende aos requisitos estabelecidos.

Engenharia de Software Prática Profissional
É a área que se interessa pelo conhecimento, habilidades e atitudes que o engenheiro de software deve ou não possuir para praticar a Engenharia de Software de forma responsável, profissional e ética.

Economia de Engenharia de Software
É a área que se preocupa em estudar valores, custos e recursos relacionado a um contexto, visando alinhar as decisões técnicas de software com os objetivos de negócios da organização, possibilitando que a empresa produtora do software permaneça de forma sustentável no mundo dos negócios.

Fundações de Computação
É a área que se preocupa com os conhecimentos da computação e seus componentes, principalmente relacionados ao ambiente operacional no qual o software evolui e executa.

Fundações matemáticas
É a área de conhecimento preocupada com os conhecimentos matemáticos que um engenheiro de software deve possuir para desenvolver um programa. Esse conhecimento está diretamente relacionado à lógica de programação que é traduzida em código/linguagem de programação.

Fundações de engenharia
É a área de conhecimento que descreve algumas das habilidades e técnicas fundamentais de engenharia que são úteis para um engenheiro de software.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 

Talvez seja melhor "fundamentos" em vez de "fundações".
