### ISSUE TITLE
Ferramentas

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/integracao#70]
Acrescente seu comentário para esta _issue_ onde você cita as ferramentas que usa ou que tem preferência para a edição de mapas mentais, conforme ilustrado abaixo:
- [MindMup](https://chrome.google.com/webstore/detail/mindmup-20-free-mind-map/mkgkheknpfngchmoaognoilfanomldfl?hl=en)

**Comment by wesleywrl** [comment]
- MindMup 
- TheBrain
- MindManager
- Mind node 
- GoConqr
- Draw.io
- Canva
- Coggle

**Comment by murilonear** [comment]
- MindMup
- Draw.io

**Comment by Murilo001** [comment]
• MindMup
• Mind Master
• Mind Mapr
• Draw.io

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. :+1:
