### ISSUE TITLE
Exemplos de mapas mentais na ES

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/integracao#71]
Existem uma infinidade de "diagramas", "infográficos" e outros que "mapeiam" a Engenharia de Software por meio de ilustrações. Também podemos dizer que são "mapas mentais", alguns no formato clássico enquanto outros não. Vamos encontrá-los? Pode incluir toda a Engenharia de Software ou apenas parte dela. Por exemplo, apenas a engenharia de requisitos. 

Acrescente os mapas mentais que encontrar por meio de comentários para esta _issue_. Naturalmente, deverá estar disponível na internet, você terá que citar o link correspondente. Este link pode ser para uma página onde está o mapa, ou um arquivo PDF, PNG ou outro.

**Comment by wesleywrl** [comment]
https://www.mindmeister.com/pt/1065804506/engenharia-de-software?fullscreen=1#
https://www.mindmeister.com/pt/635722768/engenharia-de-software?fullscreen=1#
https://www.xmind.net/embed/s5im/
https://slideplayer.com.br/slide/5640356/6/images/12/Estrutura+do+SWEBOK.jpg
https://igti.com.br/blog/wp-content/uploads/2017/10/PSI.png
https://reader020.staticloud.net/reader020/html5/20190909/5c16280e09d3f29f108c251d/bg2.png
https://i1.wp.com/www.analisederequisitos.com.br/wp-content/uploads/2019/05/infografico-o-que-e-engenharia-de-software-480x1200.png?resize=480%2C1200&ssl=1
https://i.pinimg.com/236x/33/03/c7/3303c70fe478af29b94e8c275511e847.jpg
https://w7.pngwing.com/pngs/330/122/png-transparent-software-development-web-application-development-requirement-world-wide-web-template-text-logo.png

**Comment by kirebr** [comment]
http://www.abenge.org.br/cobenge/arquivos/8/sessoestec/art1586.pdf

http://www.ceavi.udesc.br/arquivos/id_submenu/787/daniel_huebes_haendchen___uso_de_mapas_mentais_para_a_especificacao_de_requisitos.pdf

http://www.repositoriobib.ufc.br/000017/000017a1.pdf

**Comment by Murilo001** [comment]
https://www.mindmeister.com/pt/1543545219/software-engineering?fullscreen=1

https://www.pinterest.co.uk/pin/623396773406621450/visual-search/?x=15&y=15&w=475&h=599&cropSource=6

https://twitter.com/ese_unibe_ch/status/273776127095500802/photo/1

http://codingsolutioners.blogspot.com/2011/01/cseb-223-module-2-mind-map.html

**Comment by murilonear** [comment]
https://www.mindmeister.com/pt/1065804506/engenharia-de-software
https://www.mindmeister.com/pt/28311455/engenharia-de-requisitos
https://www.mindmeister.com/pt/9635700/software-design
https://www.mindmeister.com/pt/84180518/processos-de-desenvolvimento-de-software
https://www.mindmeister.com/pt/733747333/qualidade-de-software
https://www.mindmeister.com/pt/700415778/gest-o-de-projetos-de-software

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. :+1:
