### ISSUE TITLE
08

### ISSUE THREAD

**Issue by murilonear** [kyriosdata/integracao#72]
**Requisitos de Software** - Área de conhecimento que expressa as necessidades e restrições para a construção de um produto, preocupa-se com a elicitação, análise, especificação e validação de requisitos de software bem com o gerenciamento de requisitos durante todo o ciclo de vida do produto de software.

**Projeto de Software** - É a atividade do ciclo de vida da engenharia de software em que os requisitos são analisados a fim de produzir uma descrição da estrutura interna do software, são definidas a arquitetura, componentes, relações e outras características de um sistema e que serão utilizadas de base para sua construção.

**Construção de Software** - Área que tem envolvimento com todas as áreas do guia, com mais relacionamento com o projeto de software e com teste de software, são partes desta área as atividades de implementação de software, verificação, testes de unidade, testes de integração e depuração. Tem como objetivos principais minimizar a complexidade, antecipar as mudanças, efetuar a verificação e definir os padrões para a construção de software.

**Teste de Software** - É uma atividade realizada para avaliação da qualidade do produto, efetuando sua melhoria através da identificação de defeitos e problemas. É verificado o comportamento do programa com um conjunto finito de casos de testes, selecionados para confirmar o comportamento específico esperado, com o objetivo de se debater com falhas para que seja possível corrigi-los e evitar problemas futuros.

**Manutenção de Software** - É uma atividade que pode ocorrer antes ou depois da entrega do produto, são realizadas atividades de planejamento e depois, as modificações são feitas com o objetivo de corrigir as falhas, melhorar o desempenho ou adaptá-las a um ambiente externo e preservar a integridade do seu funcionamento.

**Gerência de Configuração de Software** - A área responsável por identificar a configuração de um sistema em pontos distintos no tempo com a finalidade de controlar as mudanças para configurar e manter a integridade e rastreabilidade de todos os artefatos ao longo do ciclo de vida do sistema. Suas principais atividades são o controle de versão, o controle de mudanças e a auditoria das configurações.

**Gerência de Engenharia de Software** - Área que aplica a gestão de atividades de planejamento, coordenação, medição, monitoramento, controle e comunicação de forma a garantir a manutenção sistemática e desenvolvimento dos projetos de software. Esta área influencia e recebe influência das outras áreas da Engenharia de Software, sendo fundamental para atingir um bom resultado ao final do projeto.

**Processo de Engenharia de Software** - Consiste em um conjunto de atividades inter-relacionadas que transformam uma ou mais entradas em saídas enquanto consome recursos para realizar a transformação, possuem mecanismos que proporcionam o gerenciamento automatizado do desenvolvimento de software, esta área está relacionada com a definição, implementação, controle e proposta de mudança no próprio processo.

**Métodos e Modelos de Engenharia de Software** - Esta área de conhecimento tem como objetivo pesquisar ferramentas e métodos que aumentem a produtividade dos desenvolvedores enquanto reduzem a ocorrência de falhas no desenvolvimento, os métodos impõe uma estrutura sobre a atividade de desenvolvimento e manutenção de software com o objetivo de torná-la sistemática e mais propensa ao sucesso.

**Qualidade de Software** - Está diretamente ligada com a qualidade do processo através do qual o software é desenvolvido, portanto, para se ter qualidade em um produto de software é necessário ter um processo de desenvolvimento bem definido, que deve ser documentado e acompanhado, pode-se afirmar que se algum produto ou serviço atende aos requisitos especificados, este mesmo produto ou serviço possui a qualidade desejada e a qualidade pode ser medida através do grau em que estes requisitos estão sendo atendidos.

**Engenharia de Software Prática Profissional** - Área que está preocupada com o conhecimento, habilidades e atitudes que o engenheiro de software deve possuir para praticar a engenharia de software de maneira profissional, responsável e ética.

**Economia de Engenharia de Software** - Esta área de conhecimento fornece uma visão geral sobre economia de engenharia de software, estudo do valor, custos e recursos e sua relação em um determinado contexto ou situação. A economia de engenharia de software fornece uma maneira de estudar os atributos de software e processos de software de uma forma sistemática que os relaciona às medidas econômicas, assim permitindo analisar formas de manter o negócio sustentável.

**Fundações de computação** - Área de conhecimento que engloba o conhecimento sobre o computador e seus princípios básicos de hardware e software para definir a forma do desenvolvimento e o ambiente operacional em que o software evolui e executa.

**Fundações matemáticas** - Área de conhecimento que ajuda aos engenheiros de software a compreender a lógica ao programar, uma vez que o programa segue uma lógica bem compreendida e não ambígua, a Lógica e o raciocínio lógico são a essência da matemática que um engenheiro de software deve possuir para conseguir desenvolver um programa.

**Fundações de Engenharia** - Área de conhecimento preocupada com os fundamentos de engenharia que são aplicadas a engenharia de software e outras disciplinas de engenharia, nos tópicos apresentam métodos e técnicas que são fundamentais nestas disciplinas.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 

Em vez de "fundações", melhor seria "fundamentos". Também convém observar que a engenharia de software não possui propriamente dito um ciclo de vida, quem possui um ciclo de vida é um produto de software.
