### ISSUE TITLE
MPS.BR

### ISSUE THREAD

**Issue by Campusero123** [kyriosdata/integracao#73]
i. O guia possui 49 páginas.

ii. Os processos de projeto que fazem parte do nível G são:
- Gerência de Projetos 
- Engenharia de Requisitos 
- Projeto e Construção do Produto 
- Integração do Produto  
- Verificação e Validação

iii. Os processos de projeto que se repetem dos níveis G a C são:
- Gerência de Projetos
- Engenharia de Requisitos
- Projeto e Construção do Produto
- Integração do Produto
- Verificação e Validação
Ou seja, todos os processos de projeto presentes no nível G.

iv. Na verdade, a cada nível acima, os processos sofrem evolução, se tornando mais completos, robustos e passam a ser monitorados e otimizados.

v. Apesar de terem o nome bastante semelhante, os dois tem objetivos diferentes, apesar de complementares. A Verificação, consiste em avaliar se o produto foi executado conforme o planejamento, sendo fiel aos requisitos e funcionalidades documentadas. A Validação consiste em avaliar se o produto final é consistente com as expectativas do cliente, ou seja, se atendem às regras de negócio, independentemente se o produto atendeu ou não à fidelidade aos requisitos.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. :+1:
