### ISSUE TITLE
08

### ISSUE THREAD

**Issue by Murilo001** [kyriosdata/integracao#74]
### Requisitos de Software 
Área responsável pelo levantamento dos requisitos funcionais e não-funcionais do software através de atividades como: levantamento, análise, especificação e validação. Essa área também está presente não apenas inicialmente, mas também em todo o ciclo de vida do software.

### Projeto de Software
A área de "Projeto de Software" é tanto o processo de projetar o software quanto o resultado do processo.  Durante o processo de projetar, são definidas tanto a arquitetura de alto nível com estruturação dos componentes e relacionamentos entre eles, quanto especificações de mais baixo nível como definição de classes e objetos de negócio.

### Construção de Software
A construção refere-se a etapa de criação de artefatos de software de mais baixo nível, sendo realizadas atividades como: codificação de requisitos levantados levando em conta as definições da fase de projeto, verificação de código, testes unitários e de integração, entre outras. Sendo essa a área mais essencial do ciclo de vida do desenvolvimento.

### Teste de Software
Área relacionada à qualidade que consiste em verificar se o programa está funcionando como desejado. Para isso, são definidos um conjunto de entradas que, para cada qual, existe uma saída esperada. Os testes são criados com um objetivo claro e um alvo a ser testado, que para isso utiliza diversas técnicas e meios de aferir os testes criados.

### Manutenção de Software
A Área de manutenção de software é uma fase do ciclo de vida do software que ocorre quando o software entra em ambiente de produção, obedecendo um termo de garantia ou tempo de suporte. O objetivo da manutenção é realizar modificações no software preservando a integridade do produto que está sendo utilizado pelo usuário e, para isso, reutiliza diversas outras áreas como: requisitos, projeto, construção, teste, entre outras.

### Gerência de Configuração de Software
O software é composto por diversos artefatos, desde o código fonte até documentos de requisitos e até atas de reuniões. Sendo assim, a área de gerência de configuração é responsável por armazenar, versionar e identificar artefatos de diferentes versões do software.

### Gerência de Engenharia de Software
Se tratando de uma área de conhecimento mais voltada à parte gerencial, a Gerência de Engenharia de Software é responsável por atividades como: planejamento de atividades e cronograma, coordenação do time de desenvolvimento, estimativas para definições de prazos de entregas de artefatos e desenvolvimento de relatórios. Dessa forma, mantém os stakeholders mais por dentro do andamento do projeto.

### Processo de Engenharia de Software
Área responsável pela especificação, implementação e evolução de processos de desenvolvimento de software. Especificando processos do ciclo de vida do desenvolvimento, seja do levantamento de requisitos, construção ou outros, ajuda o entendimento de "como" deve ser realizada cada atividade, facilitando a passagem de conhecimento e evolução dos processos de desenvolvimento.

### Métodos e Modelos de Engenharia de Software
Os métodos e modelos estão espalhados por todo o ciclo de vida do software, sendo que cada fase possui um conjunto de tais. A área de conhecimento de métodos e modelos se relaciona com todos os métodos/modelos das demais áreas, catalogando-os de forma que possam ser reproduzíveis em outras ocasiões.

### Qualidade de Software
A área de qualidade é responsável tanto por aspectos relacionados aos profissionais envolvidos no desenvolvimento, como: questões legais de confiabilidade de dados, código de ética, documentações pertinentes; quanto por aspectos de comunicação entre os stakeholders do projeto.

### Engenharia de Software Prática Profissional
Área relacionada a certificações na engenharia de software, engloba também código de ética, contratos de trabalhos, questões legais e outros aspectos relacionados à moralidade e legalidade junto à engenharia de software.

### Economia de Engenharia de Software
Área de conhecimento relacionada a controle à parte econômica do produto de software, seja de levantamento de custos necessários para o desenvolvimento quanto ao possível retorno financeiro, envolve estimativa de riscos e planejamento para tentar mostrar indicativos financeiros e reduzir a possibilidade do projeto entrar no vermelho.

### Fundações de Computação
Área relacionada com os fundamentos de identificação e resolução de problemas, divisão de níveis de abstrações (utilizado para transitar entre fases de requisitos e construção por exemplo), paradigmas de programação e outros aspectos da computação.

### Fundações matemáticas
Área que engloba fundamentos da matemática que são amplamente utilizados na engenharia de software, como conhecimento sobre funções matemáticas, grafos, árvores, lógica, entre outros fundamentos da matemática.

### Fundações de engenharia
Fundamentos oriundos da engenharia, como projeto, especificações e validações, níveis de escala e mensuração, entre outros fundamentos da engenharia que são aplicados à engenharia de software.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. :+1:
