### ISSUE TITLE
Revisão de itens de informação

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/integracao#80]
https://www.mindmeister.com/1672407974?t=2sGr8AvqTi#
Legenda:
(i) plano - azul 
(ii) política - verde
(iii) procedimento - roxo 
(iv) relatório - vermelho
(v) requisição - alaranjado
(vi) especificação - amarelo
Alterações:
Tradução de Fundação para fundamentos/ capacidade para capacitação/liberação para lançamento/requisição e solicitação para pedido;

**Comment by kyriosdata** [comment]
Muito bom Wesley!

COM APROVEITAMENTO. 👍
