### ISSUE TITLE
Revisão de itens de informação

### ISSUE THREAD

**Issue by Murilo001** [kyriosdata/integracao#81]
Itens alterados:
 - Revisão de Registros;
 - Fundamentos de Computação;
 - Fundamentos de Engenharia;
 - Fundamentos Matemáticos;
 - Plano de Capacidade;

Link para o mapa mental atualizado:
https://mm.tt/1677659682?t=I87kQ43Ae7

**Comment by kyriosdata** [comment]
Muito bom Murilo:

- Conceito de Operação está duplicado

COM APROVEITAMENTO. 👍
