### ISSUE TITLE
Itens de informação representativos 

### ISSUE THREAD

**Issue by kirebr** [kyriosdata/integracao#85]
Boa noite professor, o senhor disse que não conseguiu localizar a atividade. Pelo que entendi no tópico 13 nós deveríamos adicionar um * no item de informação com maior destaque para cada 1 dos 15 grupos. Eu coloquei esse * no final de cada um que achei mais representativo. Caso a atividade não seja essa, me desculpa que eu não entendi ela. Pra reforçar vou estar alterando a cor do item mais representativo. 

https://mm.tt/1685871228?t=BNQMyXe7z0

**Comment by kyriosdata** [comment]
Ok, acerca do tópico 13

COM APROVEITAMENTO. 👍
