### ISSUE TITLE
Tipos

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/integracao#86]
Possuem 6 tipos:
(i) plano: apresenta um curso sistemático de ação para atingir um propósito declarado, incluindo quando, como e por quem atividades específicas devem ser realizadas;
(ii) política: declaração clara e mensurável da direção e comportamento preferidos para condicionar as decisões tomadas
dentro de uma organização;
(iii) procedimento: item de informação que apresenta uma série ordenada de etapas para realizar um processo,atividade ou tarefa;
(iv) relatório: item de informação que descreve os resultados das atividades, tais como investigações, observações, avaliações ou testes; 
(v) requisição: item de informação, que inicia um curso de ação definido ou mudança para atender a uma necessidade
(vi) especificação: item de informação, que identifica, de forma completa precisa e verificável, os requisitos, design, comportamento ou outras características esperadas de um sistema, serviço ou processo;

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
