### ISSUE TITLE
Tipos

### ISSUE THREAD

**Issue by murilonear** [kyriosdata/integracao#88]
**Os tipos de itens de informação e seus propósitos são:**

**(I) Plano:** Definir quando, como e por quem processos ou atividades específicas devem ser realizados.

**(II) Política:** Estabelecer a intenção e abordagem de alto nível de uma organização para atingir os objetivos e garantindo o controle eficaz de um serviço, processo ou sistema de gerenciamento.

**(III) Procedimento:** Definir em detalhes quando e como realizar certos processos, atividades ou tarefas, incluindo as ferramentas necessárias.

**(IV) Relatório:** Descrever os resultados de atividades como investigações, avaliações e testes. Um relatório comunica decisões.

**(V) Requisição:** Registrar as informações necessárias para solicitar uma resposta.

**(VI) Especificação:** As especificações devem usar uma sintaxe bem definida. As especificações devem ser internamente consistentes em terminologia, definições e restrições. As especificações únicas devem ser definidas uma vez para evitar atualizações inconsistentes.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
