### ISSUE TITLE
Tipos

### ISSUE THREAD

**Issue by Murilo001** [kyriosdata/integracao#89]
### Tipos de Itens de Informação e seu propósito
1. **Especificação** 
      * Documento responsável por definir e descrever com riqueza de detalhes os requisitos da qualidade a serem cumpridos por um material, item, produto, serviço, ou processo, de forma verificável e segundo normas estabelecidas por órgãos competentes ou pela própria organização.
2. **Plano**
      * Item de informação que representa uma sequência de ações necessária para cumprir determinado objetivo, identificando para cada ação o ator, momento e local onde será realizada.
3. **Política**
      * Responsável por servir como guia de ações dentro da organização, a política é um conjunto de orientações formais que servem de base para tomada de decisões em qualquer nível de atribuição.
4. **Procedimento ** 
      * O procedimento é um item de informação que funciona como um guia ordenado de execuções detalhadas que servem para concluir uma tarefa, atividade ou processo. 
5. **Relatório**
      * O relatório é um conjunto de informações colhidas ao longo de uma reunião, atividade ou processo que é utilizado para reportar resultados parciais ou totais.
6. **Requisição**
      * A requisição é um conjunto de informações e indagações necessárias para solicitar uma mudança ou resposta para atender a necessidade levantada.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
